#define MARGIN_RATIO 0.2
#define ANGLE_MARGIN 0.175

#define FORWARD_SPEED 0.25
#define ROTATE_SPEED 0.1

#define MAZE_SIZE 12

#define WEIGHT_DISTANCE 0.2
#define WEIGHT_ACTIVE_BOMB 20
#define WEIGHT_UNACTIVE_BOMB -10
#define WEIGHT_ENEMY -1
#define WEIGHT_FRIEND -3

#define NUMBER_OF_CASES_PENALTY 3
#define DISCOUNT_FACTOR 0.75
#define WEIGHT_STILL 0