#define MARGIN_RATIO 0.2
#define ANGLE_MARGIN 0.2

#define FORWARD_SPEED 0.4
#define ROTATE_SPEED 0.2

#define FAST_FORWARD_SPEED 1.0
#define FAST_ROTATE_SPEED 0.5

#define MAZE_SIZE 12

#define CENTER_X 1.5
#define CENTER_Y 1.5

#define WEIGHT_CENTER 0.05
#define WEIGHT_NOGO 100
#define WEIGHT_DISTANCE 0.5
#define WEIGHT_ACTIVE_BOMB 100
#define WEIGHT_UNACTIVE_BOMB -5
#define WEIGHT_ENEMY 5
#define WEIGHT_FRIEND 5

#define PATH_BOMB_IMMINENT_WEIGHT 100
#define PATH_BOMB_URGENT_WEIGHT 4
#define PATH_BOMB_CHILL_WEIGHT 2
#define PATH_WALL_WEIGHT 4

#define NUMBER_OF_CASES_PENALTY 3
#define DISCOUNT_FACTOR 0.75
#define WEIGHT_STILL 5

#define MAX_DIJKSTRA_DEPTH 5

#define INITIAL_THRESHOLD 0.8
#define THRESHOLD_DECAY 0.005
#define MIN_THRESHOLD 0.001